# Generated by Django 3.2 on 2022-02-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20220120_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('first_language', models.CharField(max_length=40)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_course_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_length', models.DecimalField(decimal_places=0, max_digits=2)),
                ('course_level', models.CharField(blank=True, max_length=3, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('course_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='booking_form.booking')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
