# Generated by Django 3.2 on 2022-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='date_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='course_cost_per_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_length',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_level',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CourseBooking',
        ),
    ]
