# Generated by Django 3.2 on 2022-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0004_remove_booking_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='course',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
