# Generated by Django 3.2 on 2022-02-10 16:17

import booking_form.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0005_booking_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_length',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1, message='Minimum Course Length is 1 week')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_start_date',
            field=models.DateField(null=True, validators=[booking_form.models.Booking.no_past_dates]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(auto_now_add=True),
        ),
    ]
