# Generated by Django 3.2 on 2022-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0006_auto_20220210_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
