# Generated by Django 3.2 on 2022-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0010_booking_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='course_friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_timetable',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
