# Generated by Django 3.2 on 2022-02-15 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('current_english_level', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2- Elementary'), ('A2H', 'A2H- Pre-Intermediate'), ('B1', 'B1- Intermediate'), ('B2H', 'B2H- Upper-Intermediate'), ('C1', 'C1- Advanced')], max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
