# Generated by Django 3.2 on 2022-02-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220204_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost_per_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
