# Generated by Django 3.2 on 2022-02-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_cost_per_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='minumum_age',
            new_name='minimum_age',
        ),
    ]
