# Generated by Django 3.2 on 2022-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_minumum_age_course_minimum_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(max_length=500),
        ),
    ]
